### PR TITLE
Added American English.  Moved British English to en_GB.

### PR DESCRIPTION
**Pull request by joshreve**
Added American English voice translation to en directory.  Relocated British
English translations to en_GB.  Additional code changes required to
incorporate added words (content-en.json) and to incorporate
separation of British and American English files in the settings (ApplicationInfo.cpp).  There will be an accompanying pull request on GCompris-qt with those changes.

### CODE REVIEW

**Comment by petitlapin** [comment]
Hi, thank you for the pull request!
For the American English voices, who is the author and what is the license of the audio files? We need to add them in the LICENSE file in the voices folder.

Johnny

**Comment by joshreve** [comment]
No problem.  I'm happy to contribute.  It is a great program and I wanted
to add an american accent for my daughter.  I am the author, Joshua Shreve,
and I plan to stick with the GPL V3+ per the suggestions on the voice
contribution page.  I did leave the existing files in the words directory
in American English that were previously recorded, but those should be the
only files that are not my recordings.

I'm happy to record or re-record content if there are any issues or missing
files.  I used the json files and info in the translation files to try to
cover everything.

Let me know if you need anything else.

Thanks,

Joshua Shreve

**Comment by petitlapin** [comment]
Thank you, I updated the LICENSE file and pushed the actual work in https://cgit.kde.org/gcompris-data.git/commit/?id=4ced647beb7dcddcaa17f78b2a1dcb4b4756aded.
We will generate the corresponding rcc file soon so it will be available.

I saw the following missing files: in the intro (programmingMaze.ogg - voice: Arrange the instructions and traverse the correct path to reach the fish.) and some voices in geography:
afghanistan.ogg 	
american_samoa.ogg 	
australia.ogg 	
azerbaijan.ogg 	
bangladesh.ogg 	
bhutan.ogg 	
cambodia.ogg 	
china.ogg 	
cook_islands.ogg 	
east_timor.ogg 	
fiji.ogg 	
french_polynesia.ogg 	
georgia.ogg 	
hawaii.ogg 	
india.ogg 	
indonesia.ogg 	
iran.ogg 	
iraq.ogg 	
japan.ogg 	
jordan.ogg 	
kazakhstan.ogg 	
kiribati.ogg 	
kyrgyzstan.ogg 	
laos.ogg 	
malaysia.ogg 	
marshall_islands.ogg 	
micronesia.ogg 	
mongolia.ogg 	
myanmar.ogg 	
nepal.ogg 	
new_caledonia.ogg 	
new_zealand.ogg 	
north_korea.ogg 	
northern_mariana_islands.ogg 	
oman.ogg 	
pakistan.ogg 	
palau.ogg 	
papua_new_guinea.ogg 	
philippines.ogg 	
pitcairn_islands.ogg 	
republic_of_congo.ogg 	
saudi_arabia.ogg 	
solomon_islands.ogg 	
south_korea.ogg 	
sri_lanka.ogg 	
syria.ogg 	
taiwan.ogg 	
tajikistan.ogg 	
thailand.ogg 	
tonga.ogg 	
turkmenistan.ogg 	
tuvalu.ogg 	
united_arab_emirates.ogg 	
us_minor.ogg 	
uzbekistan.ogg 	
vanuatu.ogg 	
vietnam.ogg 	
yemen.ogg

I close this PR, if you create the new voices, please open a new one, it will be easier for us to follow.
Thank you again!

**Comment by petitlapin** [comment]
Also, we noticed the misc/welcome.ogg voice should say "Welcome to GCompris", not "Welcome", can you please update it?
And after discussing with the other maintainer, we will keep the actual "en_GB" voices as "en" voices and rename yours to "en_US" to keep the default ones as before

**Comment by joshreve** [comment]
I will try to get to the welcome and missing intros by the end of next
weekend.  Are there any other misc voice files that were more than the
filename?  I never found a good reference for the misc files besides the
file name.

It will probably be several weeks before I get to record and post process
the extra country names.  I found the translation page was updated and will
use that as my reference for completing the list.

I also noticed the strings category for the translations but have not
figured out what content that represents.

**Comment by Animtim** [comment]
The best reference for the content of the misc voices is to listen the existing english voices in the repository.

After checking your voices, I can tell there are two more little things to fix:
-by.ogg should contain the voice "times"
-equal.ogg should contain the voice "equals" (missing s)

The strings category is the text translation in the .po files.

**Pull request closed without merging**
